config/routes.rb
Gigheap::Application.routes.draw do
  	# get "jobs/new"

	resources :users
	resources :sessions, 	only: [:new, :create, :destroy]
	match '/signup', 		to: 'users#new'  # signup_path
	match '/signin', 		to: 'sessions#new'  # signin_path
	match '/signout', 		to: 'sessions#destroy', via: :delete	
  	match '/contact', 		to: 'pages#contact'  # contact_path

	#route for posting new job page
	resources :jobs
	match '/postjob', 		to: 'jobs#new'

  	root :to => 'pages#home'

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  compay     :string(255)
#  location   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Job < ActiveRecord::Base
	# following are the attributes of the model
	# and are automatically accessible to the user
  	attr_accessible :company, :location, :title, :link

	validates :title, presence: true, length: { maximum: 50 }
	validates :company, presence: true, length: { maximum: 50 }
	validates :location, presence: true, length: { maximum: 50 }
	validates :link, presence: true, length: {maximum: 255 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  attr_accessible(:email, :name, :email, :password, :password_confirmation)
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private
    def create_remember_token
     self.remember_token = SecureRandom.urlsafe_base64
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_filter :signed_in_user, only:[:create]
  	def show
  		# the following retrieves the job from the database
  		@job = Job.find(params[:id])
	end
  
  	def new
		@job = Job.new
  	end

	def index
		@jobs = Job.paginate(page: params[:page])
	end

	def create
  		require "rubygems"
		require "twitter"
		require "tweetstream"
	
		# the following line is equivalent to
		# Job.new(title: "example", company: "example", location: "example"
		# it's a hash of hashes

		@job = Job.new(params[:job])
		if @job.save
			flash[:success] = "This submission has just been tweeted!"
			redirect_to @job
			# I think this is where I should send the tweet from

			Twitter.configure do |config|
				config.consumer_key = Figaro.env.consumer_key
				config.consumer_secret = Figaro.env.consumer_secret
				config.oauth_token = Figaro.env.oauth_token
				config.oauth_token_secret = Figaro.env.oauth_token_secret
			end

			# pull three recent tweets from lady gaga
			# @tweets = Twitter.user_timeline("Mr_Hairston15", :count => 5, :result_type => "recent")
			client = Twitter::Client.new
			client.update('A ' +@job.title+' position has just been posted at Gigheap, check it out! ' +@job.link)
		else
			render 'new'
		end
	end

	private
		def signed_in_user
			store_location
			redirect_to signin_url, notice: "Please sign in." unless signed_in?
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	require "rubygems"
	require "twitter"
	require "tweetstream"

	Twitter.configure do |config|
		config.consumer_key = Figaro.env.consumer_key
		config.consumer_secret = Figaro.env.consumer_secret
		config.oauth_token = Figaro.env.oauth_token
		config.oauth_token_secret = Figaro.env.oauth_token_secret
	end

	# @tweets = Twitter.user_timeline("Mr_Hairston15", :count => 5, :result_type => "recent")

	# attempting to pull tweets with search terms
	@tweets = Twitter.search("technology information jobs", :count => 5).results
	
	# @twitter_feed = Twitter.user_timeline("ladygaga").first.text

	# playing with streaming below
	
	# @statuses = []
	# TweetStream.configure do |config|
	#	config.consumer_key = Figaro.env.consumer_key
	#	config.consumer_secret = Figaro.env.consumer_secret
	#	config.oauth_token = Figaro.env.oauth_token
	#	config.oauth_token_secret = Figaro.env.oauth_token_secret
	# end
	
	# @client = TweetStream::Client.new.track('yankess') do |status|
	#	@statuses << status.text
	#	client.stop if @tweets.size >=5
	# end
	
	# fetch job info for front page here
	@jobs = Job.all
	
	# return the first 8 records in jobs table
	#@jobs = Job.find(:all, :limit => 8)

  end
  	
  def contact
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_email(params[:session][:email].downcase)
		
		if user && user.authenticate(params[:session][:password])
			sign_in user
      		redirect_to user

		else
			flash.now[:error] = 'Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :signed_in_user, only: [:index, :edit, :update]
	before_filter :correct_user, only: [:edit, :update]
	before_filter :admin_user, only: :destroy

	def show
		@user = User.find(params[:id])
		#this is the same as using User.find(1) in the console
	end

  	def new
		@user = User.new
  	end

	def index
		@users = User.paginate(page: params[:page])
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to Gigheap!"
			redirect_to @user
		else
			# If not successful/false return to new page
			render 'new'
		end
	end

	def edit
		# this may need to come out
		# @user = User.find(params[:id])
	end

	def update
		# @user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			# Handle successful update
			flash[:success] = "Profile udpated"
			sign_in @user
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User destroyed."
		redirect_to users_url
	end

	private
		def signed_in_user
			store_location
			redirect_to signin_url, notice: "Please sign in." unless signed_in?
		end

		def correct_user
			@user = User.find(params[:id])
			redirect_to(root_path) unless current_user?(@user)
		end

		def admin_user
			redirect_to(root_path) unless current_user.admin?
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	#Returns the full title on a per-page basis
	def full_title(page_title)
		base_title = "gigheap.com"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end	
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    
    # cookie could also be implemented with expiration
    # example cookies[:remember_token] = { value: user.remember_token,
    #                                       expires: 20.years.from.now.utc }
    # note that permanent is 20 years in rails
    
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
  	user == current_user
  end

  def sign_out
  	self.current_user = nil
	cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
  	redirect_to(session[:return_to] || default)
	session.delete(:return_to)
  end

  def store_location
  	session[:return_to] = request.url
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/jobs/_job.html.erb
<li>
	<%= link_to job.title, job %>
	<%= link_to job.company, job %>
	
</li>

app/views/jobs/index.html.erb
<% provide(:title, 'All jobs') %>
<h1>All jobs</h1>

<%= will_paginate %>
<ul>
	<%= render @jobs %>
</ul>
<%= will_paginate %>

app/views/jobs/new.html.erb
<% provide(:title, 'Post Job') %>

<div class="container">
	<h2 class="center">Post Job</h2>
		<div class="row">
			<div class="span6 offset3">
				<%= form_for(@job) do |f| %>
					<%= render 'shared/job_error_messages' %>
					<%= f.label :title %>
					<%= f.text_field :title %>

					<%= f.label :company %>
					<%= f.text_field :company %>

					<%= f.label :location %>
					<%= f.text_field :location %>

					<%= f.label :link %>
					<%= f.text_field :link %>

					<%= f.submit "Create new listing", class: "btn btn-small btn-warning" %>
				<% end %>
		</div>
	</div>
</div>

app/views/jobs/show.html.erb
<% provide(:title, @job.title) %>
<div class="container">
	<h2><%= @job.title %></h2>
	<h2><%= @job.company %></h2>
	<h2><%= @job.location %></h2>
	<%= link_to "Visit Job Listing", @job.link %>
</div>

app/views/layouts/_footer.html.erb
<!-- page footer layout -->

<div class="container">
	<footer class="footer">
		<small>copyright 2013 gigheap</small>
		<!-- nav properties make it pull right -->
  		<nav>
    		<ul>
      			<li><i class="icon-envelope"></i><%= link_to " contact", contact_path %></li>
    		</ul>
  		</nav>
	</footer>
</div>

app/views/layouts/_header.html.erb
<!-- <header class="navbar navbar-fixed-top navbar-inverse"> -->
<header class="navbar navbar-fixed-top">
<div class="navbar-inner" id="top_navbar">
<div class="container">
      <%= link_to "gigheap", root_path, id: "logo" %>
	  <nav>
        <ul class="nav pull-right">
          <li><%= link_to "home", root_path %></li>
          <% if signed_in? %>
          <li><% link_to "users", users_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">account<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "profile", current_user %></li>
              <li><%= link_to "settings", edit_user_path(current_user)%></li>
              <li class="divider"></li>
              <li>
               <%= link_to "sign out", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to "sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>

<!-- application.html.erb -->

<html>
	<head>
  		<title><%= full_title(yield(:title)) %></title>
  		<%= stylesheet_link_tag    "application", :media => "all" %>
  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>
  		<%= render 'layouts/shim' %>
		<!-- adding google fonts below -->
		<!-- <link href='http://fonts.googleapis.com/css?family=Patua+One' rel='stylesheet' type='text/css'> -->
	</head>
	<body>
  		<%= render 'layouts/header' %>
  		<div class="container-fluid">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
    		<%= yield %>
    		<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
  		</div>
	</body>
</html>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Contact me at
</p>

app/views/pages/home.html.erb
<!-- outer container for main page -->
<div class="container">
	<div class="row" id="welcome_div">
		<div class="welcome_inner span7">
			<% if !signed_in? %>
	  			<h2>Welcome to gigheap!</h2>
				<p>Gigheap is a career resource for the Asheville technology community.  Employers <%= link_to "sign up", signup_path %> now and start listing jobs.  Followers of the site will recieve the listings immmediately. Job-seekers, follow us to get the latest updates!</p>		
				<!-- <%= link_to "Sign up", signup_path, class: "btn btn-small btn-warning" %> -->
		
				<!-- twitter link follows -->
  				<a href="https://twitter.com/heaptest" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @heaptest</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			<% else %>
			<div id="welcome_back">
				<p>Welcome Back!<p>
				<p><%= link_to "Post a job", postjob_path %> to let Gigheap followers know about the position.</p>
				<!-- <%= link_to "Post Job", postjob_path, class: "btn btn-small btn-primary" %> -->
			</div>
			<% end %>
		</div>	
		
		<div class="span2 offset2" id="ghlogo">
			<div>
			<%= link_to image_tag("logo.png"), root_path %>
			</div>
		</div>
			
	</div>

  	<div id="info_div" class="container">
		<div class="row-fluid">
			<div class="content_div span6">
				<p class="instructions">Recent Job Tweets:</p>
  				<% @tweets.each do |t| %>
					<p class="sub_par"><i class="icon-chevron-right"></i><%= auto_link(t.text) %></p>
  				<% end %>
			</div>
					
			<div class="content_div span6">
				<!-- <p>recent jobs</p> -->
				<p class="instructions">Recent Job Listings:</p>
				<% @jobs.each do |j| %>
					<p class="sub_par"><i class="icon-chevron-right"></i><%= link_to j.title, j %> <%= j.company %><%= j.location%></p>
				<% end %>
			</div>
		</div>
	</div>

  <!-- <%= @twitter_feed %> -->  
  <!-- remove rails image
  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
  -->
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_job_error_messages.html.erb
<!-- partial for job submission errors -->
<% if @job.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@job.errors.count, "error") %>.
		</div>
		<ul>
		<% @job.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 52 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
	<% end %>
</li>

app/views/users/edit.html.erb
<!-- edit.html.erb -->

<% provide(:title, "Edit user") %>
<div class="container">
	<h2 class="center">Update your profile</h2>

	<div class="row">
		<div class="span6 offset3">
			<%= form_for(@user) do |f| %>
				<%= render 'shared/error_messages' %>

				<%= f.label :name %>
				<%= f.text_field :name %>

				<%= f.label :email %>
				<%= f.text_field :email %>

				<%= f.label :password %>
				<%= f.password_field :password %>

				<%= f.label :password_confirmation, "Confirm Password" %>
				<%= f.password_field :password_confirmation %>

				<%= f.submit "Save changes", class: "btn btn-small btn-warning" %>
			<% end %>

			<% gravatar_for @user %>
			<a href="http://gravatar.com/emails">change</a>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="container">
	<h2 class="center">Sign up</h2>

	<div class="row">
		<div class="span6 offset3">
			<%= form_for(@user) do |f| %>
				<%= render 'shared/error_messages' %>
				<%= f.label :name %>
				<%= f.text_field :name %>

				<%= f.label :email%>
				<%= f.text_field :email %>

				<%= f.label :password %>
				<%= f.password_field :password %>

				<%= f.label :password_confirmation, "Confirmation" %>
				<%= f.password_field :password_confirmation %>

				<%= f.submit "Create", class: "btn btn-small btn-warning" %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
	<div class="row">
		<aside class="span4">
			<section>
				<h1>
					<%= gravatar_for @user %>
					<%= @user.name %>
					<%= @user.email  %>
				</h1>
			</section>
		</aside>
	</div>
</div>